apiVersion: gemfire.tanzu.vmware.com/v1
kind: GemFireCluster
metadata:
  name: gemfire1
  namespace: demo-app
spec:
  image: harbor.lab.home/library/gemfire-k8s:1.0.0
  servers:
    overrides:
      gemfireProperties:
        redis-port: "11211"