apiVersion: v1
kind: Pod
metadata:
  name: privileged
  namespace: demo
spec:
  containers:
    - name: web
      image: nginx
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 1000m
          memory: 2Gi
        limits:
          cpu: 1000m
          memory: 2Gi