apiVersion: v1
kind: Pod
metadata:
  name: quota
  namespace: demo
spec:
  containers:
    - name: web
      image: nginx
      resources:
        requests:
          cpu: 3000m
          memory: 12Gi
        limits:
          cpu: 3000m
          memory: 12Gi