apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: wildcard-tls
  namespace: istio-system
spec:
  dnsNames:
  - "*.apps.lab.home"
  - "*.databases.lab.home"
  issuerRef:
    kind: ClusterIssuer
    name: mkcert
  secretName: wildcard-tls