#@ load("@ytt:data", "data")

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: concourse
  namespace: concourse
spec:
  dnsNames:
  - #@ "concourse." + data.values.primary_domain
  issuerRef:
    kind: ClusterIssuer
    name: mkcert
  secretName: concourse-tls