apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: tanzu-observability
data:
  collector.yaml: |
    clusterName: cluster1
    enableEvents: false
    enableDiscovery: true
    flushInterval: 30s

    sinks:
    - proxyAddress: wavefront-proxy.wavefront-collector.svc.cluster.local:2878
      testMode: false
      filters:
        # Filter out generated labels
        tagExclude:
        - 'label?controller?revision*'
        - 'label?pod?template*'
        - 'annotation_kubectl_kubernetes_io_last_applied_configuration'

    sources:
      kubernetes_source:
        url: 'https://kubernetes.default.svc'
        kubeletPort: 10250
        kubeletHttps: true
        useServiceAccount: true
        insecure: true
        prefix: 'kubernetes.'

        filters:
          metricDenyList:
          - 'kubernetes.sys_container.*'

      internal_stats_source:
        prefix: 'kubernetes.'

      kubernetes_state_source:
        prefix: 'kubernetes.'

      telegraf_sources:
      # enable all telegraf plugins
      - plugins: []

    # discovery rules for auto-discovery of pods and services
    discovery:
      enable_runtime_plugins: true

      plugins:

      ##########################################################################
      # Kubernetes component auto discovery
      ##########################################################################

      # auto-discover kube DNS
      - name: kube-dns-discovery
        type: prometheus
        selectors:
          images:
          - '*kube-dns/sidecar*'
          labels:
            k8s-app:
            - kube-dns
        port: 10054
        path: /metrics
        scheme: http
        prefix: kube.dns.
        filters:
          metricAllowList:
          - 'kube.dns.http.request.duration.microseconds'
          - 'kube.dns.http.request.size.bytes'
          - 'kube.dns.http.requests.total.counter'
          - 'kube.dns.http.response.size.bytes'
          - 'kube.dns.kubedns.dnsmasq.*'
          - 'kube.dns.process.*'

      # auto-discover coredns
      - name: coredns-discovery
        type: prometheus
        selectors:
          images:
          - '*coredns:*'
          labels:
            k8s-app:
            - kube-dns
        port: 9153
        path: /metrics
        scheme: http
        prefix: kube.coredns.
        filters:
          metricAllowList:
          - 'kube.coredns.coredns.cache.*'
          - 'kube.coredns.coredns.dns.request.count.total.counter'
          - 'kube.coredns.coredns.dns.request.duration.seconds'
          - 'kube.coredns.coredns.dns.request.size.bytes'
          - 'kube.coredns.coredns.dns.request.type.count.total.counter'
          - 'kube.coredns.coredns.dns.response.rcode.count.total.counter'
          - 'kube.coredns.coredns.dns.response.size.bytes'
          - 'kube.coredns.process.*'
