#@ load("@ytt:data", "data")
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
      annotations: #! Istio overwrites these annotations but I think they need to be here so Istio knows what to scrape and merge
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"          
    spec:
      containers:
      - name: demo-app
        imagePullPolicy: Always
        image: #@ data.values.harbor_domain + "/library/demo-app:latest"
        ports:
        - containerPort: 8080
        env:
        - name: DEMO_APP_DB_TYPE
          value: test
        - name: DEMO_APP_MYSQL_HOSTNAME
          value: mysql.demo.tanzu
        - name: DEMO_APP_MYSQL_DATABASE
          value: demo-app
        - name: DEMO_APP_MYSQL_USERNAME
          value: demo-app
        - name: DEMO_APP_MYSQL_PASSWORD
          value: demo-app