#@ load("@ytt:data", "data")
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        imagePullPolicy: Always
        image: #@ data.values.harbor_domain + "/library/demo-app:latest"
        ports:
        - containerPort: 8080
        env:
        - name: DEMO_APP_DB_TYPE
          value: postgres
        - name: DEMO_APP_POSTGRES_HOSTNAME
          value: "testdb.demo.tanzu"
        - name: DEMO_APP_POSTGRES_DATABASE
          value: demo-app
        - name: DEMO_APP_POSTGRES_USERNAME
          value: demo-app
        - name: DEMO_APP_POSTGRES_PASSWORD
          value: "ksIKd6EBNWvtFoB5DVqQ6u1INFjVGD"