apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: vlan502
      protocol: layer2
      addresses:
      - 10.0.2.15-10.0.2.15
