apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgweb
  namespace: postgres-dbs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgweb
  template:
    metadata:
      labels:
        app: pgweb
    spec:
      containers:
        - name: pgweb
          image: sosedoff/pgweb:0.11.6
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: pgweb
  namespace: postgres-dbs
spec:
  type: LoadBalancer
  selector:
    app: pgweb
  ports:
    - protocol: TCP
      port: 8081
