resources:
- name: my-timer
  type: time
  source:
    interval: 720m
- name: concourse-helper
  type: docker-image
  source:
    repository: ((harbordomain))/library/concourse-helper
    tag: 1
    ca_certs:
    - domain: ((harbordomain))
      cert: |
        ((tanzu-gitops.ca_cert))
- name: tanzu-gitops
  type: git
  source:
    uri: https://github.com/techgnosis/tanzu-gitops.git
    branch: master
    paths:
      - "concourse/tasks/**"

jobs:
- name: sync-helm-charts-to-harbor
  public: true
  serial: true
  plan:
  - get: my-timer
    trigger: true
  - get: concourse-helper
  - get: tanzu-gitops
  - task: sync-tac-to-harbor
    image: concourse-helper
    file: tanzu-gitops/concourse/tasks/charts-syncer/charts-syncer.yml

