resources:
- name: tanzu-gitops
  type: git
  source:
    uri: https://github.com/techgnosis/tanzu-gitops.git
    branch: master
    paths:
     - "concourse/tasks/**"
- name: product-api-image
  type: docker-image
  source:
    repository: ((harbordomain))/library/product-api
    tag: latest
    ca_certs:
    - domain: ((harbordomain))
      cert: |
        ((tanzu-gitops.ca_cert))
- name: concourse-helper
  type: docker-image
  source:
    repository: ((harbordomain))/library/concourse-helper
    tag: 1
    ca_certs:
    - domain: ((harbordomain))
      cert: |
        ((tanzu-gitops.ca_cert))

  


jobs:
- name: deploy-to-cluster
  public: true
  serial: true
  plan:
    - get: product-api-image
      trigger: true
    - get: tanzu-gitops
    - get: concourse-helper
    - task: handoff-to-kubernetes
      file: tanzu-gitops/concourse/tasks/deploy-image/deploy-image.yml
      image: concourse-helper
      input_mapping:
        image: product-api-image
      params:
        tkgicluster: cluster1
        tkgiapi: ((tanzu-gitops.tkgi_url))
        tkgiuser: ((tanzu-gitops.tkgi_user))
        tkgipassword: ((tanzu-gitops.tkgi_password))
        harbordomain: ((harbordomain))
        namespace: product-api
        deployment: product-api
        container: product-api
        image: product-api


