type:
  kind: Role
  package: vmware.tanzu.manage.v1alpha1.iam.role
  version: v1alpha1
fullName:
  name: apps-user
meta:
  description: user can use basic deployment primitives as well as Argo deployment resources
spec:
  isDeprecated: false
  resources:
  - NAMESPACE
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - pods/log
    - secrets
    - deployments
    - configmaps
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
    - patch
  - apiGroups:
    - "argoproj.io"
    resources:
    - analysisruns
    - analysistemplates
    - clusteranalysistemplates
    - experiments
    - rollouts
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
    - patch