fullName:
  name: postgres-user
meta:
  description: postgres operator user
spec:
  isDeprecated: false
  resources:
  - NAMESPACE
  rules:
  - apiGroups: # postgres
    - sql.tanzu.vmware.com
    resources:
    - postgres
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups: # pod logs
    - ""
    resources:
    - pods
    - pods/log
    verbs:
    - get
    - list
    - watch
type:
  kind: Role
  package: vmware.tanzu.manage.v1alpha1.iam.role
  version: v1alpha1