fullName:
  name: databases-user
meta:
  description: can create an instance of any supported operator
spec:
  isDeprecated: false
  resources:
  - NAMESPACE
  rules:
  - apiGroups: # postgres
    - sql.tanzu.vmware.com
    resources:
    - postgres
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups: # gemfire
    - gemfire.tanzu.vmware.com
    resources:
    - gemfireclusters
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups: # pod logs
    - ""
    resources:
    - pods
    - pods/log
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - patch
    - watch
type:
  kind: Role
  package: vmware.tanzu.manage.v1alpha1.iam.role
  version: v1alpha1