#@ load("@ytt:data", "data")

apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: spring-petclinic
  namespace: spring-petclinic-image
spec:
  tag: #@ data.values.harbor_domain + "/library/spring-petclinic"
  serviceAccount: tbs-service-account
  builder:
    name: base
    kind: ClusterBuilder
  source:
    git:
      url: https://github.com/spring-projects/spring-petclinic.git
      revision: main